apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: app-container
    image: nginx  
    volumeMounts:
      - name: secret-volume
        mountPath: "/opt"  
        readOnly: true  
  volumes:
    - name: secret-volume
      secret:
        secretName: secret

        ---------------------------------------pod.yaml----------------------------------------

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      command: ["sleep", "infinity"]
      env:
        - name: SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: string-value
        - name: CONFIG_VALUE
          valueFrom:
            configMapKeyRef:
              name: jot-config
              key: number-value
