apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: app-container
    image: nginx  
    volumeMounts:
      - name: secret-volume
        mountPath: "/opt"  
        readOnly: true  
  volumes:
    - name: secret-volume
      secret:
        secretName: secret
