apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: nginx
      volumeMounts:
      - name: config
        mountPath: "/opt"
        readOnly: true
  volumes:
  - name: config
    configMap:
      name: configmap

